Console.WriteLine("Serdar Ortaç App");

Console.WriteLine(" Şarkılar ; ");
Console.WriteLine(" 1.Mesafe  \n 2.Şeytan \n 3.Sana Değmez \n 4.İlaç \n 5.Dansöz  \n 6.Poşet  ");

while (true)
{
    Console.Write("Seçim Yapınız :  ");
    int input = int.Parse(Console.ReadLine());
    switch (input)
{
    case 1:
        Console.WriteLine("Mesafe\r\n Bir zamanlar sevdiğin\r\n Aşkı bildiğin günler oldu mu?\r\nBana güller verdiğin\r\nTatlı nameler gerçek oldu mu?\r\nBir zamanlar sevdiğin\r\nAşkı bildiğin günler oldu mu?\r\nBana güller verdiğin\r\nTatlı nameler mevsim oldu mu?\r\nHiç yüzünden darılmak\r\nHer güzel şeye alınmak\r\nBitik ve mutsuz anılmak\r\nAlın yazımsa, sildim çoktan\r\nPeşimdem gelirsen\r\nAşk için direnirsen\r\nNerede yanlış bilirsen\r\nÇözmeyi düşünürsen\r\nBelki bir gün bulursun\r\nAma sen onu da unutursun\r\nBoşver, boşver\r\nYüreğinden yaralı, bizim hikayemiz\r\nKaderimden kalanı, silsem de gitmiyor\r\nİki sohbet aralı, bütün mesafemiz\r\nGeldim anlamıyor\r\nYüreğinden yaralı, bizim hikayemiz\r\nKaderimden kalanı, silsem de gitmiyor\r\nİki sohbet aralı, bütün mesafemiz\r\nSevdim anlamıyor\r\nBir zamanlar sevdiğin\r\nAşkı bildiğin günler oldu mu?\r\nBana güller verdiğin\r\nTatlı nameler gerçek oldu mu?\r\nBir zamanlar sevdiğin\r\nAşkı bildiğin günler oldu mu?\r\nBana güller verdiğin,\r\nTatlı nameler mevsim oldu mu?\r\nHiç yüzünden darılmak\r\nHer güzel şeye alınmak\r\nBitik ve mutsuz anılmak\r\nAlın yazımsa, sildim çoktan\r\nPeşimdem gelirsen\r\nAşk için direnirsen\r\nNerede yanlış bilirsen\r\nÇözmeyi düşünürsen\r\nBelki bir gün bulursun\r\nAma sen onu da unutursun\r\nBoşver, boşver\r\nYüreğinden yaralı, bizim hikayemiz\r\nKaderimden kalanı, silsem de gitmiyor\r\nİki sohbet aralı, bütün mesafemiz\r\nGeldim anlamıyor\r\nYüreğinden yaralı, bizim hikayemiz\r\nKaderimden kalanı, silsem de gitmiyor\r\nİki sohbet aralı, bütün mesafemiz\r\nSevdim anlamıyor\r\nYüreğinden yaralı, bizim hikayemiz\r\nKaderimden kalanı, silsem de gitmiyor\r\nİki sohbet aralı, bütün mesafemiz\r\nGeldim anlamıyor\r\nYüreğinden yaralı, bizim hikayemiz\r\nKaderimden kalanı, silsem de gitmiyor\r\nİki sohbet aralı, bütün mesafemiz\r\nGeldim anlamıyor\r\nYüreğinden yaralı, bizim hikayemiz\r\nKaderimden kalanı, silsem de gitmiyor\r\nİki sohbet aralı, bütün mesafemiz\r\nSevdim anlamıyor ");
        break;

    case 2:
        Console.WriteLine("Şeytan\r\n Nasip olsun en güzel aşktan bize, bize\r\nAdımız birer hastaya çıktı mı yüze? bakan yok\r\nSanıyorlar diz çöker aşk önümüze, önümüze\r\nBu zamanlar fazla gezenlere vize? veren yok\r\nNasip olsun en güzel aşktan bize, bize\r\nAdımız birer hastaya çıktı mı yüze? bakan yok\r\nSanıyorlar diz çöker aşk önümüze, önümüze\r\nBu zamanlar fazla gezenlere vize? veren yok\r\nHayat beni neden yoruyorsun?\r\nMadem çok günah, oyunu sen bozuyorsun\r\nSebebi çok\r\nŞeytan diyor ki yanaş şuna\r\nAdını anma sataş şuna\r\nDeli kader seni karşıma\r\nÇıkaracak mı bilen yok\r\nCan üzülür buna taş değil\r\nÇekilecek gibi aşk değil\r\nBu gönül her şeye aç değil\r\nDoyuracak mı bilen yok\r\nNasip olsun en güzel aşktan bize, bize\r\nAdımız birer hastaya çıktı mı yüze? bakan yok\r\nSanıyorlar diz çöker aşk önümüze, önümüze\r\nBu zamanlar fazla gezenlere vize? veren yok\r\nNasip olsun en güzel aşktan bize, bize\r\nAdımız birer hastaya çıktı mı yüze? bakan yok\r\nSanıyorlar diz çöker aşk önümüze, önümüze\r\nBu zamanlar fazla gezenlere vize? veren yok\r\nHayat beni neden yoruyorsun?\r\nMadem çok günah, oyunu sen bozuyorsun\r\nSebebi çok\r\nŞeytan diyor ki yanaş şuna\r\nAdını anma sataş şuna\r\nDeli kader seni karşıma\r\nÇıkaracak mı bilen yok\r\nCan üzülür buna taş değil\r\nÇekilecek gibi aşk değil\r\nBu gönül her şeye aç değil\r\nDoyuracak mı bilen yok\r\nŞeytan diyor ki yanaş şuna\r\nAdını anma sataş şuna\r\nDeli kader seni karşıma\r\nÇıkaracak mı bilen yok\r\nCan üzülür buna taş değil\r\nÇekilecek gibi aşk değil\r\nBu gönül her şeye aç değil\r\nDoyuracak mı bilen yok\r\nSebebi çok\r\nŞeytan diyor ki yanaş şuna\r\nAdını anma sataş şuna\r\nDeli kader seni karşıma\r\nÇıkaracak mı bilen yok\r\nCan üzülür buna taş değil\r\nÇekilecek gibi aşk değil\r\nBu gönül her şeye aç değil\r\nDoyuracak mı bilen yok ");
        break;

    case 3:
        Console.WriteLine("Sana Değmez\r\n Sen beni ömründe bir an sevseydin\r\nBenden sana dert olmaz bunu bil\r\nNasıl güllerin pembe dilleri varsa\r\nSenin gülden bedenin var bunu bil\r\nVerdiğin en mükemmel aşk ızdırabım\r\nBoş yere etme şikayet tutar ahım\r\nBir kere insan yerine koy aşkımı\r\nSevdim anlatamadım\r\nSana değmez bu sitemler sana değmez\r\nKalbime bir hançer sapla vur gitsin\r\nBeni aldattın bunu bile bile kahrettin\r\nSana kızmıyorum, sana son sözüm unut gitsin\r\nSana değmez bu sitemler sana değmez\r\nKalbime bir hançer sapla vur gitsin\r\nBeni aldattın bunu bile bile kahrettin\r\nSana kızmıyorum, sana son sözüm unut gitsin\r\nSen beni ömründe bir an sevseydin\r\nBenden sana dert olmaz bunu bil\r\nNasıl güllerin pembe dilleri varsa\r\nSenin gülden bedenin var bunu bil\r\nVerdiğin en mükemmel aşk ızdırabım\r\nBoş yere etme şikayet tutar ahım\r\nBir kere insan yerine koy aşkımı\r\nSevdim anlatamadım\r\nSana değmez bu sitemler sana değmez\r\nKalbime bir hançer sapla vur gitsin\r\nBeni aldattın bunu bile bile kahrettin\r\nSana kızmıyorum, sana son sözüm unut gitsin\r\nSana değmez bu sitemler sana değmez\r\nKalbime bir hançer sapla vur gitsin\r\nBeni aldattın bunu bile bile kahrettin\r\nSana kızmıyorum, sana son sözüm unut gitsin\r\nSana değmez bu sitemler sana değmez\r\nKalbime bir hançer sapla vur gitsin\r\nBeni aldattın bunu bile bile kahrettin\r\nSana kızmıyorum, sana son sözüm unut gitsin\r\nSana değmez bu sitemler sana değmez\r\nKalbime bir hançer sapla vur gitsin\r\nBeni aldattın bunu bile bile kahrettin\r\nSana kızmıyorum, sana son sözüm unut gitsin");
        break;

    case 4:
        Console.WriteLine("İlaç\r\n Sakın yorulma kalp ağrısı geçer\r\nBir tek senin mi aşk acın var\r\nNe olmuş ki yavrum, ilk kez mi aşıksın\r\nAşkın doğasında gözyaşı var\r\nDün gece dışarıya çıkmışsın\r\nBambaşka kollara uçmuşsun\r\nDuydum ki, ölümüne içmişsin\r\nSayemde derbeder olmuşsun\r\nİlaç verdi mi doktor, kalp ağrısına\r\nSöndürsün söyle yavrum, o kankaların\r\nGına geldi mi benden, için şişti mi?\r\nDindirsin şimdi yavrum yalakaların\r\nİlaç verdi mi doktor, kalp ağrısına\r\nSöndürsün söyle yavrum, o kankaların\r\nGına geldi mi benden, için şişti mi?\r\nDindirsin şimdi yavrum yalakaların\r\nSakın yorulma kalp ağrısı geçer\r\nBir tek senin mi aşk acın var\r\nNe olmuş ki yavrum, ilk kez mi aşıksın\r\nAşkın doğasında gözyaşı var\r\nDün gece dışarıya çıkmışsın\r\nBambaşka kollara uçmuşsun\r\nDuydum ki, ölümüne içmişsin\r\nSayemde derbeder olmuşsun\r\nİlaç verdi mi doktor, kalp ağrısına\r\nSöndürsün söyle yavrum, o kankaların\r\nGına geldi mi benden, için şişti mi?\r\nDindirsin şimdi yavrum yalakaların\r\nDün gece dışarıya çıkmışsın\r\nBambaşka kollara uçmuşsun\r\nDuydum ki, ölümüne içmişsin\r\nSayemde derbeder olmuşsun\r\nİlaç verdi mi doktor, kalp ağrısına\r\nSöndürsün söyle yavrum, o kankaların\r\nGına geldi mi benden, için şişti mi?\r\nDindirsin şimdi yavrum yalakaların\r\nİlaç verdi mi doktor, kalp ağrısına\r\nSöndürsün söyle yavrum, o kankaların\r\nGına geldi mi benden, için şişti mi?\r\nDindirsin şimdi yavrum yalakaların");
        break;

    case 5:
        Console.WriteLine("Dansöz\r\n Binlerce dansöz var\r\nBinlerce dansöz var\r\nİtiraf, ediyorum sana itiraf\r\nBaşladı, yaralı aşklara tadilat\r\nMasumum, dışarıdan daha masumum\r\nMaalesef, bunun için sana mecburum\r\nYüksek uçan kuşun, yüreği sarhoşun\r\nAcı çeker gibi, kölesi olmuşum\r\nKavga edenlere, bana küsenlere\r\nYüreği çark edip, geri dönenlere\r\nAffet diyen kim?\r\nEz geç diyen kim?\r\nAşktan çeken kim?\r\nBenim kadar\r\nÖlene kadar aşık olamazsın\r\nBirisi çıkar onu anlayamazsın\r\nSen o tür oyunlara katlanamazsın\r\nSenin bi' kalbin var (var, var)\r\nHadi diyelim biri çok deli sevdi\r\nSenin için her şeyi her şeyi verdi\r\nYa b'r gün olur sana bel kıvırırsa\r\nBinlerce dansöz var\r\nİtiraf, ediyorum sana itiraf\r\nBaşladı, yaralı aşklara tadilat\r\nMasumum, dışarıdan daha masumum\r\nMaalesef, bunun için sana mecburum\r\nYüksek uçan kuşun, yüreği sarhoşun\r\nAcı çeker gibi, kölesi olmuşum\r\nKavga edenlere, bana küsenlere\r\nYüreği çark edip, geri dönenlere\r\nAffet diyen kim?\r\nEz geç diyen kim?\r\nAşktan çeken kim?\r\nBenim kadar\r\nÖlene kadar aşık olamazsın\r\nBirisi çıkar onu anlayamazsın\r\nSen o tür oyunlara katlanamazsın\r\nSenin bi' kalbin var (var, var)\r\nHadi diyelim biri çok deli sevdi\r\nSenin için her şeyi her şeyi verdi\r\nYa bi' gün olur sana bel kıvırırsa\r\nBinlerce dansöz var (var, var)\r\nÖlene kadar aşık olamazsın\r\nBirisi çıkar onu anlayamazsın\r\nSen o tür oyunlara katlanamazsın\r\nSenin bi' kalbin var\r\nHadi diyelim biri çok deli sevdi\r\nSenin için her şeyi her şeyi verdi\r\nYa bi' gün olur sana bel kıvırırsa\r\nBinlerce dansöz var\r\nÖlene kadar aşık olamazsın\r\nBirisi çıkar onu anlayamazsın\r\nSen o tür oyunlara katlanamazsın\r\nSenin bi' kalbin var\r\nHadi diyelim biri çok deli sevdi\r\nSenin için her şeyi her şeyi verdi\r\nYa bi' gün olur sana bel kıvırırsa\r\nBinlerce dansöz var");
        break;

        case 6:
        Console.WriteLine("Poşet\r\n Ben ne sana taparım, ne seni ararım, ne trip atarım\r\nSen ne beni oyala, ne omuz ovala, işime bakarım\r\nBen o nazı çekemem, günaha giremem, kötü söz edemem\r\nAşk bu kızıl ötesi, yaralı müzesi, hareket edemem\r\nAcılarım heveste, güneş açar aheste, bir kapalı kafesteyim\r\nTopu topu bi deste, ara sıra bi besle, iki nota bir besteyim\r\nSeni çöpe atacağım poşete yazık\r\nBi sigara yakacağım ateşe yazık\r\nAşk gidene acımak mı?\r\nBu yükü taşımak mı?\r\nYarayı kaşımak mı?\r\nSor iyisi çıkacak mı?\r\nİçime akacak mı?\r\nVe güneş açacak mı?\r\nAşk gidene acımak mı?\r\nBu yükü taşımak mı?\r\nYarayı kaşımak mı?\r\nSor iyisi çıkacak mı?\r\nİçime akacak mı?\r\nVe güneş açacak mı?\r\nBen ne sana taparım, ne seni ararım, ne trip atarım\r\nSen ne beni oyala, ne omuz ovala, işime bakarım\r\nBen o nazı çekemem, günaha giremem, kötü söz edemem\r\nAşk bu kızıl ötesi, yaralı müzesi, hareket edemem\r\nAcılarım heveste, güneş açar aheste, bir kapalı kafesteyim\r\nTopu topu bi deste, ara sıra bi besle, iki nota bir besteyim\r\nSeni çöpe atacağım poşete yazık\r\nBi sigara yakacağım ateşe yazık\r\nAşk gidene acımak mı?\r\nBu yükü taşımak mı?\r\nYarayı kaşımak mı?\r\nSor iyisi çıkacak mı?\r\nİçime akacak mı?\r\nVe güneş açacak mı?\r\nAşk gidene acımak mı?\r\nBu yükü taşımak mı?\r\nYarayı kaşımak mı?\r\nSor iyisi çıkacak mı?\r\nİçime akacak mı?\r\nVe güneş açacak mı?\r\nAşk gidene acımak mı?\r\nBu yükü taşımak mı?\r\nYarayı kaşımak mı?\r\nSor iyisi çıkacak mı?\r\nİçime akacak mı?\r\nVe güneş açacak mı?\r\nAşk gidene acımak mı?\r\nBu yükü taşımak mı?\r\nYarayı kaşımak mı?\r\nSor iyisi çıkacak mı?\r\nİçime akacak mı?\r\nVe güneş açacak mı?");
        break;

    default:
        Console.WriteLine("Hatalı seçim yaptınız ! ");
        break;
}
}
